name: todo_list_yandex_school_2024
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  uuid: ^4.4.0
  hexcolor: ^3.0.1
  provider: ^6.1.2
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:
  uses-material-design: true
  generate: true
